version: "3.8"

services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__MyAppDb: Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      MinIO__Endpoint: minio:9000
      MinIO__PublicBaseUrl: ${MINIO_PUBLIC_BASE_URL}
      MinIO__AccessKey: ${MINIO_ROOT_USER}
      MinIO__SecretKey: ${MINIO_ROOT_PASSWORD}
      MinIO__BucketName: ${MINIO_BUCKET_NAME}
      MinIO__UseSSL: false
      JwtSettings__Secret: ${JWT_SECRET}
      JwtSettings__ExpiryMinutes: ${JWT_EXPIRY_MINUTES}
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - myApp_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - myApp-db:/var/lib/postgresql/data/
    networks:
      - myApp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:latest
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    restart: unless-stopped
    command: server /data --console-address ":9001" --address ":9000"
    networks:
      - myApp_network
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "mc alias set local http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD && mc ls local",
        ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 40s

networks:
  myApp_network:
    driver: bridge

volumes:
  myApp-db:
  minio-data:
